services:
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=secret'
      - 'RABBITMQ_DEFAULT_USER=myuser'
    ports:
      - '5672'
  db:
    image: mysql/mysql-server:latest
    container_name: db
    restart: always
    environment:
      - MYSQL_DATABASE=gpedidos
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/0_init.sql
volumes:
  mysql-volume:
    driver: local
